import { createFileRoute } from "@tanstack/react-router";
import { Database, RotateCcw, Radio } from "lucide-react";

import { useGuardian } from "../state/guardian";
import { ZONE_THRESHOLDS } from "../services/gridService";

export const Route = createFileRoute("/settings")({
  head: () => ({
    meta: [
      { title: "Settings — GridGuardian" },
      {
        name: "description",
        content:
          "Grid data source, carbon-intensity thresholds, estimation assumptions and progress management for GridGuardian.",
      },
      { property: "og:title", content: "Settings — GridGuardian" },
      {
        property: "og:description",
        content: "Inspect the data source and scientific assumptions behind your rewards.",
      },
    ],
  }),
  component: SettingsPage,
});

function SettingsPage() {
  const { grid, resetProgress } = useGuardian();

  return (
    <div className="max-w-2xl space-y-5 animate-rise">
      <header>
        <h1 className="text-3xl font-semibold sm:text-4xl">Settings</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Transparency about where the numbers come from.
        </p>
      </header>

      <section className="glass p-5">
        <h2 className="flex items-center gap-2 text-sm font-semibold">
          <Radio className="h-4 w-4 text-secondary" /> Grid data source
        </h2>
        <p className="mt-2 text-sm text-muted-foreground">
          Currently: <span className="text-warning">{grid?.providerLabel ?? "loading…"}</span>.
          Values are generated by a simulated provider that mirrors a real daily carbon curve —
          they are not real-world measurements. The Grid Service exposes a single provider
          interface, so a live carbon-intensity API can replace it without UI changes.
        </p>
      </section>

      <section className="glass p-5">
        <h2 className="flex items-center gap-2 text-sm font-semibold">
          <Database className="h-4 w-4 text-primary" /> Assumptions
        </h2>
        <ul className="mt-3 space-y-2 text-sm text-muted-foreground">
          <li>
            Clean grid below <span className="num text-primary">{ZONE_THRESHOLDS.clean}</span>{" "}
            gCO₂e/kWh · critical at or above{" "}
            <span className="num text-destructive">{ZONE_THRESHOLDS.critical}</span>.
          </li>
          <li>Grid multipliers: 1× clean, 1.5× moderate, 3× critical.</li>
          <li>Streak bonuses: +10% at 3 days, +20% at 7 days, +35% at 14 days.</li>
          <li>Avoided CO₂ assumes 12 W of device load released for the session duration.</li>
          <li>Progress is stored locally in this browser.</li>
        </ul>
      </section>

      <section className="glass p-5">
        <h2 className="flex items-center gap-2 text-sm font-semibold">
          <RotateCcw className="h-4 w-4 text-destructive" /> Reset
        </h2>
        <p className="mt-2 text-sm text-muted-foreground">
          Clears coins, sessions, city and challenge progress.
        </p>
        <button
          onClick={resetProgress}
          className="mt-4 rounded-xl border border-border px-4 py-2.5 text-sm font-medium text-destructive transition-colors hover:bg-destructive/10"
        >
          Reset my progress
        </button>
      </section>
    </div>
  );
}
