/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CityRouteImport } from './routes/city'
import { Route as ShieldRouteImport } from './routes/shield'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CityRoute = CityRouteImport.update({
  id: '/city',
  path: '/city',
  getParentRoute: () => rootRouteImport,
} as any)
const ShieldRoute = ShieldRouteImport.update({
  id: '/shield',
  path: '/shield',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/shield': typeof ShieldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/shield': typeof ShieldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/city': typeof CityRoute
  '/shield': typeof ShieldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/city' | '/shield'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/city' | '/shield'
  id: '__root__' | '/' | '/city' | '/shield'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CityRoute: typeof CityRoute
  ShieldRoute: typeof ShieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city': {
      id: '/city'
      path: '/city'
      fullPath: '/city'
      preLoaderRoute: typeof CityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shield': {
      id: '/shield'
      path: '/shield'
      fullPath: '/shield'
      preLoaderRoute: typeof ShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CityRoute: CityRoute,
  ShieldRoute: ShieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
